services:
  casaos:
    image: dockurr/casa:latest
    container_name: casaos
    privileged: true
    restart: unless-stopped
    ports:
      - "8085:8080"      # Web UI
    volumes:
      - ./data:/data   # Persistent storage
      - /var/run/docker.sock:/var/run/docker.sock