version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.4.1@sha256:082cfc67d08a896d7be240f203ec0ba76f9e34a928b67df5a5f1cd671144a90c
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://umbrel-2.local:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400

